hidden: []
faked: []
fakedDisabled: []
# OPTIONS ARE CASE SENSITIVE
# RED     DARK_RED
# AQUA    DARK_AQUA
# BLUE    DARK_BLUE
# GRAY    DARK_GRAY
# GREEN   DARK_GREEN
# WHITE   BLACK
# YELLOW  GOLD
# LIGHT_PURPLE  DARK_PURPLE
ColorFaked:     "YELLOW"
ColorHidden:    "GOLD"
ColorEnabled:   "GREEN"
ColorDisabled:  "RED"
ColorDefault:   "WHITE"